/*Murilo*/

CREATE DATABASE prueba8;

USE prueba8;  

CREATE TABLE employees (
	id VARCHAR(6) NOT NULL,
	password VARCHAR(12) NOT NULL,
	name VARCHAR(25) NOT NULL,
	surname VARCHAR(50) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	admin BOOLEAN NOT NULL,
	CONSTRAINT PK_EMP PRIMARY KEY(id)
);

CREATE TABLE clients(
	dni VARCHAR(13) NOT NULL,
	name VARCHAR(25) NOT NULL,
	surname VARCHAR(50) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	address VARCHAR(100) NOT NULL,
	region VARCHAR(15) NOT NULL,
	CONSTRAINT PK_CLIENT PRIMARY KEY(dni)
);


CREATE TABLE pets(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(25) NOT NULL,
	type VARCHAR(25) NOT NULL,
	price FLOAT(20) NOT NULL,
	sold BOOLEAN NOT NULL,
	CONSTRAINT PK_PET PRIMARY KEY(id)
);


CREATE TABLE sales(
	id INT NOT NULL AUTO_INCREMENT,
	pet INT NOT NULL,
	client VARCHAR(13) NOT NULL,
	employee VARCHAR(6) NOT NULL,
	CONSTRAINT PK_SALE PRIMARY KEY(id),
	CONSTRAINT FK_SALE_PET FOREIGN KEY(pet) REFERENCES pets(id),
	CONSTRAINT FK_SALE_CLI FOREIGN KEY(client) REFERENCES clients(dni),
	CONSTRAINT FK_SALE_EMP FOREIGN KEY(employee) REFERENCES employees(id)
);
